export const WEBHOOK_EVENT_TYPES = {
  // Apple events
  DID_RENEW: 'DID_RENEW',
  DID_FAIL_TO_RENEW: 'DID_FAIL_TO_RENEW',
  DID_CHANGE_RENEWAL_STATUS: 'DID_CHANGE_RENEWAL_STATUS',
  SUBSCRIBED: 'SUBSCRIBED',
  EXPIRED: 'EXPIRED',
  GRACE_PERIOD_EXPIRED: 'GRACE_PERIOD_EXPIRED',
  REFUND: 'REFUND',
  // Google events
  SUBSCRIPTION_PURCHASED: 'SUBSCRIPTION_PURCHASED',
  SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_CANCELED: 'SUBSCRIPTION_CANCELED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_ON_HOLD: 'SUBSCRIPTION_ON_HOLD',
  SUBSCRIPTION_IN_GRACE_PERIOD: 'SUBSCRIPTION_IN_GRACE_PERIOD',
  SUBSCRIPTION_RECOVERED: 'SUBSCRIPTION_RECOVERED',
} as const;

export type WebhookEventType = (typeof WEBHOOK_EVENT_TYPES)[keyof typeof WEBHOOK_EVENT_TYPES];
